(() => {
  const cfg = window.GEO_CONFIG || {};
  const configured = Boolean(cfg.supabaseUrl && cfg.supabaseAnonKey && !cfg.supabaseUrl.includes('YOUR_SUPABASE') && !cfg.supabaseAnonKey.includes('YOUR_SUPABASE') && window.supabase?.createClient);
  const client = configured ? window.supabase.createClient(cfg.supabaseUrl, cfg.supabaseAnonKey) : null;
  const K={users:'geo_demo_users_v4',session:'geo_demo_session_v4',content:'geo_demo_content_v4',settings:'geo_demo_settings_v4',progress:'geo_demo_progress_v4'};
  const now=()=>new Date().toISOString();
  const makeId=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
  const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  function ensureDemo(){
    const users=read(K.users,[]), defaults=[
      {id:'demo-student-1',email:'student@demo.mn',password:'student123',full_name:'Демо Сурагч',school:'Томужин альтернатив сургууль',subject:'Газарзүй',grade:'7',role:'student',status:'active',created_at:now()},
      {id:'demo-student-2',email:'student2@demo.mn',password:'student123',full_name:'Бат Эрдэнэ',school:'Томужин альтернатив сургууль',subject:'Газарзүй',grade:'7',role:'student',status:'active',created_at:now()},
      {id:'demo-teacher-1',email:'teacher@demo.mn',password:'teacher123',full_name:'Демо Багш',school:'Томужин альтернатив сургууль',subject:'Газарзүй',grade:'',role:'teacher',status:'active',created_at:now()},
      {id:'demo-admin-1',email:'admin@demo.mn',password:'admin123',full_name:'Системийн Админ',school:'Geo Education Mongolia',subject:'',grade:'',role:'admin',status:'active',created_at:now()}
    ];
    defaults.forEach(d=>{if(!users.some(u=>u.id===d.id||u.email.toLowerCase()===d.email.toLowerCase()))users.push(d)});write(K.users,users);
    const content=read(K.content,[]), samples=[
      {id:'sample-1',owner_id:'demo-teacher-1',teacher_name:'Демо Багш',content_type:'lesson',title:'Монгол орны газарзүйн байрлал',description:'7-р ангийн танилцуулга хичээл',grade:'7',subject:'Газарзүй',resource_type:'link',external_url:'https://www.youtube.com/',file_path:'',file_name:'',due_at:null,published:true,max_score:null,grade_weight:0,created_at:now(),updated_at:now()},
      {id:'sample-2',owner_id:'demo-teacher-1',teacher_name:'Демо Багш',content_type:'assignment',title:'Газрын зургийн тэмдэглэгээ',description:'7-р ангийн гэрийн даалгаврын жишээ',grade:'7',subject:'Газарзүй',resource_type:'link',external_url:'https://docs.google.com/',file_path:'',file_name:'',due_at:null,published:true,max_score:20,grade_weight:40,created_at:now(),updated_at:now()},
      {id:'sample-3',owner_id:'demo-teacher-1',teacher_name:'Демо Багш',content_type:'exam',title:'I бүлгийн сорил',description:'7-р ангийн жишиг шалгалт',grade:'7',subject:'Газарзүй',resource_type:'link',external_url:'https://forms.google.com/',file_path:'',file_name:'',due_at:null,published:true,max_score:50,grade_weight:60,created_at:now(),updated_at:now()}
    ];
    samples.forEach(x=>{if(!content.some(c=>c.id===x.id))content.push(x)});write(K.content,content);
    if(!read(K.settings,null))write(K.settings,{site_title:'Сонирхолтой Газарзүй',registration_open:true,teacher_registration_open:true,student_registration_open:true,teacher_can_publish:true,support_email:'support@example.mn'});
    const progress=read(K.progress,[]);
    if(!progress.some(p=>p.id==='demo-progress-1')) progress.push({id:'demo-progress-1',student_id:'demo-student-1',content_id:'sample-1',status:'completed',opened_at:now(),last_opened_at:now(),completed_at:now(),score:null,teacher_feedback:'',created_at:now(),updated_at:now()});
    if(!progress.some(p=>p.id==='demo-progress-2')) progress.push({id:'demo-progress-2',student_id:'demo-student-1',content_id:'sample-2',status:'completed',opened_at:now(),last_opened_at:now(),completed_at:now(),score:18,teacher_feedback:'Сайн ажилласан.',created_at:now(),updated_at:now()});
    write(K.progress,progress);
  }
  ensureDemo();

  async function getProfileByUser(user){if(!user)return null;if(!configured)return read(K.users,[]).find(u=>u.id===user.id)||null;const{data,error}=await client.from('profiles').select('*').eq('id',user.id).single();if(error)throw error;return data}
  async function getSession(){if(!configured){const s=read(K.session,null);if(!s)return{user:null,profile:null};const p=read(K.users,[]).find(u=>u.id===s.userId)||null;return{user:p?{id:p.id,email:p.email}:null,profile:p}}const{data,error}=await client.auth.getSession();if(error)throw error;const user=data.session?.user||null;return{user,profile:user?await getProfileByUser(user):null}}
  function accountStatusMessage(status){
    if(status==='pending') return 'Таны бүртгэл админы баталгаажуулалт хүлээж байна. Батлагдсаны дараа нэвтрэх боломжтой.';
    if(status==='rejected') return 'Таны бүртгэлийг админ батлаагүй байна. Сургуулийн админтай холбогдоно уу.';
    if(status==='suspended') return 'Таны хэрэглэгчийн эрх түр хаагдсан байна. Сургуулийн админтай холбогдоно уу.';
    return 'Энэ хэрэглэгч одоогоор нэвтрэх эрхгүй байна.';
  }
  async function signIn(email,password){if(!configured){const u=read(K.users,[]).find(x=>x.email.toLowerCase()===email.toLowerCase()&&x.password===password);if(!u)throw new Error('И-мэйл эсвэл нууц үг буруу байна.');if(u.status!=='active')throw new Error(accountStatusMessage(u.status));write(K.session,{userId:u.id,created_at:now()});return{user:{id:u.id,email:u.email},profile:u}}const{data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;const profile=await getProfileByUser(data.user);if(profile?.status!=='active'){await client.auth.signOut();throw new Error(accountStatusMessage(profile?.status))}return{user:data.user,profile}}
  async function signUpUnified({role,email,password,fullName,school,subject,grade}){const settings=await getSettings();if(!['teacher','student'].includes(role))throw new Error('Багш эсвэл Сурагч гэдгээ сонгоно уу.');if(settings.registration_open===false)throw new Error('Шинэ бүртгэл одоогоор хаалттай байна.');if(role==='teacher'&&settings.teacher_registration_open===false)throw new Error('Багшийн бүртгэл хаалттай байна.');if(role==='student'&&settings.student_registration_open===false)throw new Error('Сурагчийн бүртгэл хаалттай байна.');if(role==='student'&&!['7','8','9','10','11','12'].includes(String(grade)))throw new Error('Ангиа зөв сонгоно уу.');
    if(!configured){const users=read(K.users,[]);if(users.some(u=>u.email.toLowerCase()===email.toLowerCase()))throw new Error('Энэ и-мэйлээр бүртгэл аль хэдийн байна.');const u={id:makeId(),email,password,full_name:fullName,school,subject:role==='teacher'?(subject||'Газарзүй'):'Газарзүй',grade:role==='student'?String(grade):'',role,status:'pending',created_at:now()};users.push(u);write(K.users,users);return{user:{id:u.id,email:u.email},profile:{...u,password:undefined},needsEmailConfirmation:false,pendingApproval:true}}
    const{data,error}=await client.auth.signUp({email,password,options:{data:{full_name:fullName,school,subject:role==='teacher'?(subject||'Газарзүй'):'Газарзүй',grade:role==='student'?String(grade):'',requested_role:role}}});if(error)throw error;if(data.session)await client.auth.signOut();return{user:data.user,profile:null,needsEmailConfirmation:!data.session,pendingApproval:true};
  }
  async function signOut(){if(!configured){localStorage.removeItem(K.session);return}await client.auth.signOut()}
  async function getSettings(){if(!configured)return read(K.settings,{});const{data,error}=await client.from('app_settings').select('settings').eq('id',1).single();if(error)throw error;return data?.settings||{}}
  async function saveSettings(settings){if(!configured){write(K.settings,settings);return settings}const{data,error}=await client.from('app_settings').update({settings}).eq('id',1).select().single();if(error)throw error;return data.settings}

  async function listContent({ownerId=null}={}){if(!configured){let a=read(K.content,[]);if(ownerId)a=a.filter(x=>x.owner_id===ownerId);return a.sort((a,b)=>new Date(b.updated_at)-new Date(a.updated_at))}let q=client.from('content_items').select('*').order('updated_at',{ascending:false});if(ownerId)q=q.eq('owner_id',ownerId);const{data,error}=await q;if(error)throw error;return data||[]}
  async function saveContent(item,file){const s=await getSession();if(!s.user)throw new Error('Нэвтэрсэн хэрэглэгч олдсонгүй.');const payload={...item,owner_id:s.user.id,teacher_name:s.profile?.full_name||'Багш',max_score:item.content_type==='lesson'?null:Number(item.max_score||0),grade_weight:item.content_type==='lesson'?0:Number(item.grade_weight||0),updated_at:now()};
    if(!configured){let a=read(K.content,[]);if(file){payload.file_name=file.name;payload.file_path='demo-file';payload.external_url=''}if(payload.id){const i=a.findIndex(x=>x.id===payload.id);if(i<0)throw new Error('Агуулга олдсонгүй.');a[i]={...a[i],...payload}}else{payload.id=makeId();payload.created_at=now();a.push(payload)}write(K.content,a);return payload}
    let filePath=payload.file_path||'',fileName=payload.file_name||'';if(file){filePath=`${s.user.id}/${makeId()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const{error:upErr}=await client.storage.from('course-files').upload(filePath,file,{upsert:false});if(upErr)throw upErr;fileName=file.name}
    const dbPayload={owner_id:s.user.id,teacher_name:payload.teacher_name,content_type:payload.content_type,title:payload.title,description:payload.description,grade:String(payload.grade),subject:payload.subject,resource_type:payload.resource_type,external_url:payload.resource_type==='link'?payload.external_url:'',file_path:filePath,file_name:fileName,due_at:payload.due_at||null,published:Boolean(payload.published),max_score:payload.max_score,grade_weight:payload.grade_weight};
    if(payload.id){const{data,error}=await client.from('content_items').update(dbPayload).eq('id',payload.id).select().single();if(error)throw error;return data}const{data,error}=await client.from('content_items').insert(dbPayload).select().single();if(error)throw error;return data
  }
  async function deleteContent(item){if(!configured){write(K.content,read(K.content,[]).filter(x=>x.id!==item.id));write(K.progress,read(K.progress,[]).filter(p=>p.content_id!==item.id));return}if(item.file_path)await client.storage.from('course-files').remove([item.file_path]);const{error}=await client.from('content_items').delete().eq('id',item.id);if(error)throw error}
  async function togglePublished(item,published){if(!configured){const a=read(K.content,[]),i=a.findIndex(x=>x.id===item.id);if(i>=0){a[i].published=published;a[i].updated_at=now();write(K.content,a)}return}const{error}=await client.from('content_items').update({published}).eq('id',item.id);if(error)throw error}
  async function openResource(item){if(!item)throw new Error('Материал олдсонгүй.');if(item.resource_type==='link'){if(!item.external_url)throw new Error('Линк оруулаагүй байна.');window.open(item.external_url,'_blank','noopener');return}if(!item.file_path){if(item.file_name)throw new Error('Demo горимд локал файл серверт хадгалагдахгүй. Supabase холбоно уу.');throw new Error('Файл олдсонгүй.')}if(!configured)throw new Error('Файл нээхийн тулд Supabase Storage холбоно уу.');const{data,error}=await client.storage.from('course-files').createSignedUrl(item.file_path,3600);if(error)throw error;window.open(data.signedUrl,'_blank','noopener')}
  async function listStudentContent(grade){const a=await listContent();return a.filter(x=>x.published&&String(x.grade)===String(grade))}

  async function listStudentProgress(){const s=await getSession();if(!s.user)return[];if(!configured)return read(K.progress,[]).filter(p=>p.student_id===s.user.id);const{data,error}=await client.from('student_progress').select('*').eq('student_id',s.user.id);if(error)throw error;return data||[]}
  async function touchStudentProgress(contentId,action='open'){
    const s=await getSession();if(!s.user||s.profile?.role!=='student')throw new Error('Сурагчийн бүртгэл шаардлагатай.');const t=now();
    if(!configured){const a=read(K.progress,[]);let p=a.find(x=>x.student_id===s.user.id&&x.content_id===contentId);if(!p){p={id:makeId(),student_id:s.user.id,content_id:contentId,status:'in_progress',opened_at:t,last_opened_at:t,completed_at:null,score:null,teacher_feedback:'',created_at:t,updated_at:t};a.push(p)}if(action==='open'){p.opened_at=p.opened_at||t;p.last_opened_at=t;if(p.status==='pending')p.status='in_progress'}if(action==='complete'){p.status='completed';p.completed_at=t;p.updated_at=t}if(action==='pending'){p.status='in_progress';p.completed_at=null;p.updated_at=t}write(K.progress,a);return p}
    const{data:existing,error:selErr}=await client.from('student_progress').select('*').eq('student_id',s.user.id).eq('content_id',contentId).maybeSingle();if(selErr)throw selErr;let payload={student_id:s.user.id,content_id:contentId};if(action==='open'){payload.opened_at=existing?.opened_at||t;payload.last_opened_at=t;payload.status=existing?.status==='completed'?'completed':'in_progress'}if(action==='complete'){payload.status='completed';payload.completed_at=t}if(action==='pending'){payload.status='in_progress';payload.completed_at=null}if(existing){const{data,error}=await client.from('student_progress').update(payload).eq('id',existing.id).select().single();if(error)throw error;return data}const{data,error}=await client.from('student_progress').insert({...payload,opened_at:payload.opened_at||t,last_opened_at:t,status:payload.status||'in_progress'}).select().single();if(error)throw error;return data
  }
  async function setStudentProgress(contentId,status){return touchStudentProgress(contentId,status==='completed'?'complete':'pending')}

  async function listTeacherStudents(){const s=await getSession();if(!s.user)return[];if(!configured)return read(K.users,[]).filter(u=>u.role==='student'&&u.status==='active'&&(!s.profile?.school||u.school===s.profile.school)).sort((a,b)=>(a.grade||'').localeCompare(b.grade||'')||(a.full_name||'').localeCompare(b.full_name||''));const{data,error}=await client.from('profiles').select('*').eq('role','student').eq('status','active').order('grade').order('full_name');if(error)throw error;return data||[]}
  async function listTeacherProgress(ownerId){if(!configured){const owned=read(K.content,[]).filter(c=>c.owner_id===ownerId),ids=new Set(owned.map(c=>c.id));return read(K.progress,[]).filter(p=>ids.has(p.content_id))}const{data,error}=await client.from('student_progress').select('*');if(error)throw error;return data||[]}
  async function saveGrade(contentId,studentId,score,feedback=''){
    const t=now();if(!configured){const a=read(K.progress,[]);let p=a.find(x=>x.student_id===studentId&&x.content_id===contentId);if(!p){p={id:makeId(),student_id:studentId,content_id:contentId,status:'in_progress',opened_at:null,last_opened_at:null,completed_at:null,created_at:t};a.push(p)}p.score=score===''||score==null?null:Number(score);p.teacher_feedback=feedback;p.updated_at=t;write(K.progress,a);return p}
    const{data:existing,error:selErr}=await client.from('student_progress').select('*').eq('student_id',studentId).eq('content_id',contentId).maybeSingle();if(selErr)throw selErr;const payload={score:score===''||score==null?null:Number(score),teacher_feedback:feedback};if(existing){const{data,error}=await client.from('student_progress').update(payload).eq('id',existing.id).select().single();if(error)throw error;return data}const{data,error}=await client.from('student_progress').insert({student_id:studentId,content_id:contentId,status:'pending',...payload}).select().single();if(error)throw error;return data
  }

  async function listUsers(){if(!configured)return read(K.users,[]).map(({password,...u})=>u);const{data,error}=await client.from('profiles').select('*').order('created_at',{ascending:false});if(error)throw error;return data||[]}
  async function updateUser(userId,patch){if(!configured){const a=read(K.users,[]),i=a.findIndex(u=>u.id===userId);if(i>=0){a[i]={...a[i],...patch};write(K.users,a);return a[i]}throw new Error('Хэрэглэгч олдсонгүй.')}const{data,error}=await client.from('profiles').update(patch).eq('id',userId).select().single();if(error)throw error;return data}

  window.GeoBackend={mode:configured?'supabase':'demo',client,getSession,signIn,signUpUnified,signOut,getSettings,saveSettings,listContent,saveContent,deleteContent,togglePublished,openResource,listStudentContent,listStudentProgress,touchStudentProgress,setStudentProgress,listTeacherStudents,listTeacherProgress,saveGrade,listUsers,updateUser};
})();
