const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let studentSession=null,studentItems=[],studentProgress=[],aiHistory=[];
const typeLabel={lesson:'Хичээл',assignment:'Даалгавар',exam:'Шалгалт'},resourceLabel={video:'Видео',ppt:'PowerPoint',word:'Word',pdf:'PDF',link:'Линк',other:'Файл'};
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(d,withTime=false){if(!d)return'—';try{return new Intl.DateTimeFormat('mn-MN',withTime?{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}:{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(d))}catch{return'—'}}
function tab(name){$$('.nav-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.tab-page').forEach(p=>p.classList.toggle('active',p.id===`tab-${name}`));$('#studentTopTitle').textContent={overview:'Хяналтын самбар',lessons:'Хичээлүүд',assignments:'Даалгавар',exams:'Шалгалт',grades:'Миний дүн',ai:'AI чат багш'}[name]||'Сурагчийн самбар'}
$$('.nav-tab').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$$('[data-tab-jump]').forEach(b=>b.onclick=()=>tab(b.dataset.tabJump));
function progressFor(id){return studentProgress.find(p=>p.content_id===id)}
function rowsHtml(rows,empty=null){if(!rows.length)return empty||'<div class="empty"><b>Одоогоор материал алга.</b>Багш энэ ангид материал нийтлэх үед энд харагдана.</div>';return`<div class="table-wrap"><table class="data-table"><thead><tr><th>Материал</th><th>Төрөл</th><th>Багш</th><th>Хугацаа</th><th>Төлөв</th><th>Үйлдэл</th></tr></thead><tbody>${rows.map(x=>{const p=progressFor(x.id),done=p?.status==='completed';return`<tr><td class="title-cell"><b>${esc(x.title)}</b><small>${esc(x.description||'Тайлбаргүй')}</small></td><td><span class="pill ${x.content_type==='lesson'?'green':x.content_type==='assignment'?'blue':'purple'}">${esc(typeLabel[x.content_type]||x.content_type)} · ${esc(resourceLabel[x.resource_type]||x.resource_type)}</span></td><td>${esc(x.teacher_name||'Багш')}</td><td>${x.due_at?fmt(x.due_at):'—'}</td><td><span class="pill ${done?'green':p?.opened_at?'blue':'orange'}">${done?'Гүйцэтгэсэн':p?.opened_at?'Үзэж эхэлсэн':'Хүлээгдэж байна'}</span></td><td><div class="actions"><button class="icon-action" data-student-open="${x.id}">Нээх</button><button class="icon-action" data-student-done="${x.id}">${done?'Буцаах':'✓ Гүйцэтгэсэн'}</button></div></td></tr>`}).join('')}</tbody></table></div>`}
function filtered(type,extra=null){const q=$(`.student-search[data-type="${type}"]`)?.value.toLowerCase().trim()||'';return studentItems.filter(x=>x.content_type===type&&(!extra||extra(x))&&(!q||`${x.title} ${x.description} ${x.subject} ${x.teacher_name}`.toLowerCase().includes(q)))}
function baselineItems(){return studentItems.filter(x=>x.content_type==='exam'&&x.exam_kind==='baseline')}
function gradeData(){const assessments=studentItems.filter(x=>['assignment','exam'].includes(x.content_type));let final=0,totalW=0;const rows=assessments.map(x=>{const p=progressFor(x.id),max=Number(x.max_score||0),w=Number(x.grade_weight||0),score=p?.score;totalW+=w;if(score!=null&&max>0)final+=(Number(score)/max)*w;return{x,p,max,w,score,contribution:score!=null&&max>0?(Number(score)/max)*w:0}});return{rows,final,totalW}}
function gradesHtml(){const {rows,final,totalW}=gradeData();if(!rows.length)return'<div class="empty"><b>Үнэлгээ хараахан алга.</b>Багш даалгавар, шалгалтын дүнгийн тохиргоо оруулах үед энд харагдана.</div>';return`<div class="grade-summary student-grade-summary"><div><b>Одоогийн нийт дүн</b><span><strong>${final.toFixed(1)}%</strong> / тохируулсан ${totalW}% жин</span></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Үнэлгээ</th><th>Төрөл</th><th>Оноо</th><th>Жин</th><th>Дүнд нэмэгдэх</th><th>Багшийн тайлбар</th></tr></thead><tbody>${rows.map(r=>`<tr><td class="title-cell"><b>${esc(r.x.title)}</b><small>${esc(r.x.teacher_name||'Багш')}</small></td><td><span class="pill ${r.x.content_type==='assignment'?'blue':'purple'}">${typeLabel[r.x.content_type]}</span></td><td>${r.score==null?'—':`${Number(r.score)} / ${r.max}`}</td><td>${r.w}%</td><td>${r.score==null?'—':`${r.contribution.toFixed(1)}%`}</td><td>${esc(r.p?.teacher_feedback||'—')}</td></tr>`).join('')}</tbody></table></div>`}
function renderStudent(){const {final}=gradeData();$('#studentLessonCount').textContent=studentItems.filter(x=>x.content_type==='lesson').length;$('#studentAssignmentCount').textContent=studentItems.filter(x=>x.content_type==='assignment').length;$('#studentExamCount').textContent=studentItems.filter(x=>x.content_type==='exam').length;$('#studentFinalGrade').textContent=`${final.toFixed(1)}%`;$('#studentRecent').innerHTML=rowsHtml(studentItems.slice(0,5));$('#studentLessonTable').innerHTML=rowsHtml(filtered('lesson'));$('#studentAssignmentTable').innerHTML=rowsHtml(filtered('assignment'));$('#studentExamTable').innerHTML=rowsHtml(filtered('exam',x=>x.exam_kind!=='baseline'));renderBaseline();$('#studentGradesTable').innerHTML=gradesHtml();bindStudentActions()}
function renderBaseline(){
  const list=baselineItems(),box=$('#studentBaselineTable'),badge=$('#baselineBadge');
  if(box)box.innerHTML=rowsHtml(list,'<div class="empty"><b>Гарааны үнэлгээ хараахан алга.</b>Багш гарааны үнэлгээ нийтлэх үед энд хамгийн түрүүнд харагдана.</div>');
  if(!badge)return;
  if(!list.length){badge.textContent='Алга';badge.className='pill';return}
  const done=list.filter(x=>progressFor(x.id)?.status==='completed').length;
  badge.textContent=done===list.length?'Гүйцэтгэсэн':`${done}/${list.length} гүйцэтгэсэн`;
  badge.className=`pill ${done===list.length?'green':'orange'}`;
}
function bindStudentActions(){
  $$('[data-student-open]').forEach(b=>b.onclick=async()=>{const x=studentItems.find(i=>i.id===b.dataset.studentOpen);try{await GeoBackend.touchStudentProgress(x.id,'open');studentProgress=await GeoBackend.listStudentProgress();renderStudent();await GeoBackend.openResource(x)}catch(e){alert(e.message)}});
  $$('[data-student-done]').forEach(b=>b.onclick=async()=>{const x=studentItems.find(i=>i.id===b.dataset.studentDone),p=progressFor(x.id);try{await GeoBackend.setStudentProgress(x.id,p?.status==='completed'?'pending':'completed');await loadStudent()}catch(e){alert(e.message)}});
}
$$('.student-search').forEach(el=>el.addEventListener('input',renderStudent));
async function loadStudent(){[studentItems,studentProgress]=await Promise.all([GeoBackend.listStudentContent(studentSession.profile.grade),GeoBackend.listStudentProgress()]);renderStudent()}
$('#studentLogoutBtn').onclick=async()=>{await GeoBackend.signOut();location.href='/auth'};

function addAiMessage(role,text){const div=document.createElement('div');div.className=`ai-message ${role}`;div.innerHTML=`<b>${role==='assistant'?'AI багш':'Та'}</b><p>${esc(text).replace(/\n/g,'<br>')}</p>`;$('#aiChat').appendChild(div);$('#aiChat').scrollTop=$('#aiChat').scrollHeight}
$('#aiForm').addEventListener('submit',async e=>{e.preventDefault();const input=$('#aiInput'),text=input.value.trim();if(!text)return;addAiMessage('user',text);aiHistory.push({role:'user',content:text});input.value='';const btn=$('#aiSendBtn');btn.disabled=true;btn.textContent='Бодож байна...';$('#aiStatus').textContent='AI багш хариулж байна...';try{
  if(GeoBackend.mode==='demo')throw new Error('AI чатны интерфэйс бэлэн байна. Жинхэнэ AI хариулт авахын тулд эхлээд Supabase болон Netlify AI function-ийг холбоно уу.');
  const {data:{session:sbSession}}=await GeoBackend.client.auth.getSession();const token=sbSession?.access_token;if(!token)throw new Error('AI багш ашиглахын тулд дахин нэвтэрнэ үү.');
  const res=await fetch('/.netlify/functions/ai-teacher',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({message:text,history:aiHistory.slice(0,-1).slice(-8)})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'AI үйлчилгээ одоогоор холбогдоогүй байна.');const answer=data.answer||'Хариу ирсэнгүй.';addAiMessage('assistant',answer);aiHistory.push({role:'assistant',content:answer});$('#aiStatus').textContent='AI зөвлөгөө алдаа гаргаж болох тул чухал мэдээллийг багш, сурах бичгээс давхар шалгаарай.'
}catch(err){addAiMessage('assistant',err.message||'AI холболтын тохиргоог SETUP.md файлаас шалгана уу.');$('#aiStatus').textContent='AI холболтын тохиргоог SETUP.md файлаас харна уу.'}finally{btn.disabled=false;btn.textContent='Илгээх →'}});

(async()=>{try{studentSession=await GeoBackend.getSession();if(!studentSession.user||studentSession.profile?.role!=='student'||studentSession.profile?.status!=='active'){if(studentSession.user)await GeoBackend.signOut();location.href='/auth';return}const n=studentSession.profile.full_name||'Сурагч',g=studentSession.profile.grade||'7';$('#studentSideName').textContent=n;$('#studentSideEmail').textContent=studentSession.user.email;$('#studentWelcomeName').textContent=n.split(' ')[0];$('#studentGradeBadge').textContent=`${g}-р анги`;$('#studentGradeText').textContent=`${g}-р анги`;if(GeoBackend.mode==='demo')$('#studentDemoNotice').classList.remove('hidden');else{$('#studentBackendBadge').textContent='LIVE';$('#studentBackendBadge').classList.add('live')}await loadStudent()}catch(e){console.error(e);location.href='/auth'}})();
