const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let session=null, items=[], students=[], teacherProgress=[], editing=null;
const typeLabel={lesson:'Хичээл',assignment:'Даалгавар',exam:'Шалгалт'};
const resourceLabel={video:'Видео',ppt:'PowerPoint',word:'Word',pdf:'PDF',link:'Линк',other:'Файл'};
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(d,withTime=false){if(!d)return'—';try{return new Intl.DateTimeFormat('mn-MN',withTime?{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}:{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(d))}catch{return'—'}}
function tab(name){$$('.nav-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.tab-page').forEach(p=>p.classList.toggle('active',p.id===`tab-${name}`));$('#topTitle').textContent={overview:'Хяналтын самбар',lessons:'Хичээлүүд',assignments:'Даалгавар',exams:'Шалгалт',gradebook:'Дүн ба ахиц'}[name]||'Багшийн самбар';if(name==='gradebook')renderGradebook()}
$$('.nav-tab').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$$('[data-tab-jump]').forEach(b=>b.onclick=()=>tab(b.dataset.tabJump));
function filtered(type){const q=$(`.content-search[data-type="${type}"]`)?.value.toLowerCase().trim()||'',g=$(`.grade-filter[data-type="${type}"]`)?.value||'';return items.filter(x=>x.content_type===type&&(!g||String(x.grade)===g)&&(!q||`${x.title} ${x.description} ${x.subject}`.toLowerCase().includes(q)))}
function rowsHtml(rows){if(!rows.length)return'<div class="empty"><b>Агуулга хараахан алга.</b>“Агуулга нэмэх” товчоор шинээр үүсгэнэ үү.</div>';return`<div class="table-wrap"><table class="data-table"><thead><tr><th>Агуулга</th><th>Төрөл</th><th>Анги</th><th>Дүнгийн жин</th><th>Төлөв</th><th>Үйлдэл</th></tr></thead><tbody>${rows.map(x=>`<tr><td class="title-cell"><b>${esc(x.title)}</b><small>${esc(x.description||'Тайлбаргүй')}</small></td><td><span class="pill ${x.content_type==='lesson'?'green':x.content_type==='assignment'?'blue':'purple'}">${esc(typeLabel[x.content_type]||x.content_type)} · ${esc(resourceLabel[x.resource_type]||x.resource_type)}</span></td><td>${esc(x.grade)}-р</td><td>${x.content_type==='lesson'?'—':`${Number(x.max_score||0)} оноо · ${Number(x.grade_weight||0)}%`}</td><td><span class="pill ${x.published?'green':'orange'}">${x.published?'Нийтэлсэн':'Ноорог'}</span></td><td><div class="actions"><button class="icon-action" data-open="${x.id}">Нээх</button><button class="icon-action" data-edit="${x.id}">Засах</button><button class="icon-action" data-delete="${x.id}">Устгах</button></div></td></tr>`).join('')}</tbody></table></div>`}
function render(){
  $('#lessonCount').textContent=items.filter(x=>x.content_type==='lesson').length;$('#assignmentCount').textContent=items.filter(x=>x.content_type==='assignment').length;$('#examCount').textContent=items.filter(x=>x.content_type==='exam').length;$('#studentCountTeacher').textContent=students.length;
  $('#recentContent').innerHTML=rowsHtml(items.slice(0,5));$('#lessonTable').innerHTML=rowsHtml(filtered('lesson'));$('#assignmentTable').innerHTML=rowsHtml(filtered('assignment'));$('#examTable').innerHTML=rowsHtml(filtered('exam'));bindContentActions();refreshAssessmentFilter();
}
function bindContentActions(){
  $$('[data-open]').forEach(b=>b.onclick=async()=>{const x=items.find(i=>i.id===b.dataset.open);try{await GeoBackend.openResource(x)}catch(e){alert(e.message)}});
  $$('[data-edit]').forEach(b=>b.onclick=()=>openDialog(items.find(i=>i.id===b.dataset.edit)));
  $$('[data-delete]').forEach(b=>b.onclick=async()=>{const x=items.find(i=>i.id===b.dataset.delete);if(confirm(`“${x.title}” материалыг устгах уу?`)){try{await GeoBackend.deleteContent(x);await load()}catch(e){alert(e.message)}}});
}
$$('.content-search').forEach(el=>el.addEventListener('input',render));$$('.grade-filter').forEach(el=>el.addEventListener('change',render));
function syncFields(){const rt=$('#resourceType').value,type=$('#contentType').value;$('#fileField').classList.toggle('hidden',rt==='link');$('#linkField').classList.toggle('hidden',rt!=='link');$('#dueField').classList.toggle('hidden',type==='lesson');$('#gradingFields').classList.toggle('hidden',type==='lesson');$('#maxScore').required=type!=='lesson';$('#gradeWeight').required=type!=='lesson'}
$('#resourceType').onchange=syncFields;$('#contentType').onchange=syncFields;
function openDialog(x=null,forcedType=null){editing=x;$('#contentForm').reset();$('#formError').classList.remove('show');$('#contentId').value=x?.id||'';$('#existingFilePath').value=x?.file_path||'';$('#existingFileName').value=x?.file_name||'';$('#contentType').value=x?.content_type||forcedType||'lesson';$('#grade').value=x?.grade||'7';$('#contentTitle').value=x?.title||'';$('#description').value=x?.description||'';$('#subject').value=x?.subject||session?.profile?.subject||'Газарзүй';$('#resourceType').value=x?.resource_type||'video';$('#externalUrl').value=x?.external_url||'';$('#dueAt').value=x?.due_at?new Date(x.due_at).toISOString().slice(0,16):'';$('#published').value=String(x?.published??true);$('#maxScore').value=x?.max_score??100;$('#gradeWeight').value=x?.grade_weight??10;$('#currentFile').textContent=x?.file_name||'байхгүй';$('#dialogTitle').textContent=x?'Агуулга засах':'Шинэ агуулга нэмэх';syncFields();$('#contentModal').classList.add('open')}
function closeDialog(){$('#contentModal').classList.remove('open');editing=null}
$('#dialogClose').onclick=closeDialog;$('#cancelDialog').onclick=closeDialog;$('#contentModal').onclick=e=>{if(e.target.id==='contentModal')closeDialog()};$('#newContentBtn').onclick=()=>openDialog();$$('[data-new]').forEach(b=>b.onclick=()=>openDialog(null,b.dataset.new));
$('#contentForm').addEventListener('submit',async e=>{e.preventDefault();const err=$('#formError');err.classList.remove('show');const btn=$('#saveContentBtn');btn.disabled=true;btn.textContent='Хадгалж байна...';try{const file=$('#resourceFile').files[0]||null;if(file&&file.size>50*1024*1024)throw new Error('Файл 50MB-аас их байна. Том видеог YouTube/Vimeo линкээр оруулахыг зөвлөж байна.');const rt=$('#resourceType').value,type=$('#contentType').value;if(rt==='link'&&!$('#externalUrl').value.trim())throw new Error('Веб линк оруулна уу.');if(rt!=='link'&&!file&&!editing?.file_path&&!editing?.file_name)throw new Error('Файл сонгоно уу.');if(type!=='lesson'&&Number($('#maxScore').value)<=0)throw new Error('Дээд оноо 0-ээс их байх ёстой.');await GeoBackend.saveContent({id:$('#contentId').value||null,file_path:$('#existingFilePath').value,file_name:$('#existingFileName').value,content_type:type,title:$('#contentTitle').value.trim(),description:$('#description').value.trim(),grade:$('#grade').value,subject:$('#subject').value.trim(),resource_type:rt,external_url:$('#externalUrl').value.trim(),due_at:$('#dueAt').value?new Date($('#dueAt').value).toISOString():null,published:$('#published').value==='true',max_score:$('#maxScore').value,grade_weight:$('#gradeWeight').value},file);closeDialog();await load()}catch(ex){err.textContent=ex.message||'Хадгалахад алдаа гарлаа.';err.classList.add('show')}finally{btn.disabled=false;btn.textContent='Хадгалах'}});

function assessmentsForGrade(g=''){return items.filter(x=>['assignment','exam'].includes(x.content_type)&&(!g||String(x.grade)===String(g)))}
function selectableForGrade(g=''){return items.filter(x=>(!g||String(x.grade)===String(g))).sort((a,b)=>String(a.grade).localeCompare(String(b.grade))||String(a.title).localeCompare(String(b.title)))}
function refreshAssessmentFilter(){const sel=$('#assessmentFilter'),cur=sel.value,g=$('#gradebookGrade').value;const a=selectableForGrade(g);sel.innerHTML='<option value="">Бүх агуулга / үнэлгээ</option>'+a.map(x=>`<option value="${x.id}">${esc(x.grade)}-р · ${typeLabel[x.content_type]||x.content_type} · ${esc(x.title)}</option>`).join('');if(a.some(x=>x.id===cur))sel.value=cur}
function pFor(studentId,contentId){return teacherProgress.find(p=>p.student_id===studentId&&p.content_id===contentId)}
function latestActivity(studentId){const ps=teacherProgress.filter(p=>p.student_id===studentId);const dates=ps.flatMap(p=>[p.last_opened_at,p.completed_at,p.updated_at].filter(Boolean)).map(d=>new Date(d));return dates.length?new Date(Math.max(...dates)) : null}
function studentFinal(student,assessments){let total=0,totalWeight=0;assessments.forEach(a=>{const w=Number(a.grade_weight||0),max=Number(a.max_score||0),p=pFor(student.id,a.id);if(w>0&&max>0){totalWeight+=w;if(p?.score!=null)total+=(Number(p.score)/max)*w}});return{score:total,weight:totalWeight}}
function renderGradebook(){
  refreshAssessmentFilter();const g=$('#gradebookGrade').value,cid=$('#assessmentFilter').value;let st=students.filter(s=>!g||String(s.grade)===g);const ass=assessmentsForGrade(g),selected=cid?items.find(x=>x.id===cid):null,isGradable=selected&&['assignment','exam'].includes(selected.content_type);const totalWeight=ass.reduce((n,x)=>n+Number(x.grade_weight||0),0);
  $('#gradeWeightSummary').innerHTML=`<div><b>Үнэлгээний бүтэц</b><span>${ass.length} даалгавар/шалгалт · Нийт жин <strong class="${Math.abs(totalWeight-100)<.01?'ok-weight':'warn-weight'}">${totalWeight}%</strong></span></div>${selected?`<div class="selected-assessment">Сонгосон: <b>${esc(selected.title)}</b> · ${typeLabel[selected.content_type]||selected.content_type}${isGradable?` · ${Number(selected.max_score||0)} оноо · ${Number(selected.grade_weight||0)}%`:' · үзсэн хугацааг хянах'}</div>`:'<div class="selected-assessment">Агуулга сонговол тухайн хичээлийг нээсэн/гүйцэтгэсэн хугацаа харагдана. Даалгавар эсвэл шалгалт сонговол оноо, тайлбар оруулж болно.</div>'}`;
  if(!st.length){$('#gradebookTable').innerHTML='<div class="empty"><b>Сурагч олдсонгүй.</b>Таны сургуультай ижил бүртгэлтэй сурагчид энд харагдана.</div>';return}
  const rows=st.map(s=>{const target=selected||null,p=target?pFor(s.id,target.id):null,fin=studentFinal(s,ass);return`<tr><td class="title-cell"><b>${esc(s.full_name||'Нэргүй')}</b><small>${esc(s.email||'')} · ${esc(s.grade||'—')}-р анги</small></td><td>${isGradable?`<input class="score-input" data-score-student="${s.id}" type="number" min="0" max="${Number(target.max_score||100)}" step="0.1" value="${p?.score??''}" placeholder="0 / ${Number(target.max_score||0)}">`:target?'—':'—'}</td><td>${isGradable?`<input class="feedback-input" data-feedback-student="${s.id}" value="${esc(p?.teacher_feedback||'')}" placeholder="Тайлбар">`:target?'—':'Нийт дүн'}</td><td>${target?fmt(p?.opened_at,true):fmt(latestActivity(s.id),true)}</td><td>${target?fmt(p?.completed_at,true):`${fin.score.toFixed(1)}%`}</td><td>${isGradable?`<button class="icon-action" data-save-grade="${s.id}">Хадгалах</button>`:target?`<span class="pill ${p?.completed_at?'green':p?.opened_at?'blue':'orange'}">${p?.completed_at?'Гүйцэтгэсэн':p?.opened_at?'Үзсэн':'Нээгээгүй'}</span>`:`<span class="pill ${fin.score>=80?'green':fin.score>=60?'blue':'orange'}">${fin.score.toFixed(1)} / ${fin.weight||0}%</span>`}</td></tr>`}).join('');
  $('#gradebookTable').innerHTML=`<div class="table-wrap"><table class="data-table grade-table"><thead><tr><th>Сурагч</th><th>${isGradable?'Оноо':'Оноо'}</th><th>${isGradable?'Багшийн тайлбар':selected?'Төлөв':'Тайлбар'}</th><th>${selected?'Анх нээсэн':'Сүүлд идэвх'}</th><th>${selected?'Гүйцэтгэсэн':'Нийт дүн'}</th><th>Үйлдэл</th></tr></thead><tbody>${rows}</tbody></table></div>`;
  if(isGradable)$$('[data-save-grade]').forEach(b=>b.onclick=async()=>{const sid=b.dataset.saveGrade,score=$(`[data-score-student="${sid}"]`).value,feedback=$(`[data-feedback-student="${sid}"]`).value;try{if(score!==''&&(Number(score)<0||Number(score)>Number(selected.max_score||100)))throw new Error(`Оноо 0–${selected.max_score} хооронд байна.`);b.disabled=true;b.textContent='...';await GeoBackend.saveGrade(selected.id,sid,score,feedback);teacherProgress=await GeoBackend.listTeacherProgress(session.user.id);renderGradebook()}catch(e){alert(e.message)}finally{b.disabled=false}})
}
$('#gradebookGrade').onchange=()=>{refreshAssessmentFilter();renderGradebook()};$('#assessmentFilter').onchange=renderGradebook;
function exportExcel(){
  const g=$('#gradebookGrade').value,ass=assessmentsForGrade(g),allContent=selectableForGrade(g),st=students.filter(s=>!g||String(s.grade)===g),gradeRows=[],activityRows=[];
  st.forEach(s=>{
    ass.forEach(a=>{const p=pFor(s.id,a.id);gradeRows.push({'Сурагч':s.full_name,'И-мэйл':s.email,'Анги':`${s.grade}-р анги`,'Төрөл':typeLabel[a.content_type],'Үнэлгээ':a.title,'Дээд оноо':Number(a.max_score||0),'Авсан оноо':p?.score??'','Жин %':Number(a.grade_weight||0),'Анх нээсэн':fmt(p?.opened_at,true),'Сүүлд нээсэн':fmt(p?.last_opened_at,true),'Гүйцэтгэсэн':fmt(p?.completed_at,true),'Багшийн тайлбар':p?.teacher_feedback||''})});
    const fin=studentFinal(s,ass);gradeRows.push({'Сурагч':s.full_name,'И-мэйл':s.email,'Анги':`${s.grade}-р анги`,'Төрөл':'НИЙТ','Үнэлгээ':'Эцсийн дүн','Дээд оноо':'','Авсан оноо':fin.score.toFixed(1),'Жин %':fin.weight,'Анх нээсэн':'','Сүүлд нээсэн':'','Гүйцэтгэсэн':'','Багшийн тайлбар':''});
    allContent.forEach(c=>{const p=pFor(s.id,c.id);activityRows.push({'Сурагч':s.full_name,'И-мэйл':s.email,'Анги':`${s.grade}-р анги`,'Төрөл':typeLabel[c.content_type]||c.content_type,'Агуулга':c.title,'Анх нээсэн':fmt(p?.opened_at,true),'Сүүлд нээсэн':fmt(p?.last_opened_at,true),'Гүйцэтгэсэн':fmt(p?.completed_at,true),'Төлөв':p?.completed_at?'Гүйцэтгэсэн':p?.opened_at?'Үзсэн':'Нээгээгүй'})})
  });
  if(!gradeRows.length&&!activityRows.length)return alert('Экспортлох мэдээлэл алга.');
  if(window.XLSX){const wb=XLSX.utils.book_new();if(gradeRows.length)XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(gradeRows),'Дүн ба шалгалт');if(activityRows.length)XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(activityRows),'Үзсэн хугацаа');XLSX.writeFile(wb,`tomujin-gradebook-${g||'all'}-${new Date().toISOString().slice(0,10)}.xlsx`)}else{const rows=gradeRows.length?gradeRows:activityRows,keys=Object.keys(rows[0]),csv='\ufeff'+[keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replace(/"/g,'""')}"`).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='tomujin-gradebook.csv';a.click();URL.revokeObjectURL(a.href)}
}
$('#exportExcelBtn').onclick=exportExcel;
async function load(){[items,students,teacherProgress]=await Promise.all([GeoBackend.listContent({ownerId:session.user.id}),GeoBackend.listTeacherStudents(),GeoBackend.listTeacherProgress(session.user.id)]);render();if($('#tab-gradebook').classList.contains('active'))renderGradebook()}
$('#logoutBtn').onclick=async()=>{await GeoBackend.signOut();location.href='/auth'};
(async()=>{try{session=await GeoBackend.getSession();if(!session.user||!session.profile||!['teacher','admin'].includes(session.profile.role)){location.href='/auth';return}if(session.profile.status!=='active'){await GeoBackend.signOut();location.href='/auth';return}$('#sideName').textContent=session.profile.full_name||'Багш';$('#sideEmail').textContent=session.user.email;$('#welcomeName').textContent=(session.profile.full_name||'Багш').split(' ')[0];if(GeoBackend.mode==='demo')$('#demoNotice').classList.remove('hidden');else{$('#backendBadge').textContent='LIVE';$('#backendBadge').classList.add('live')}await load()}catch(e){console.error(e);location.href='/auth'}})();
